[Distribution]
Distribution=debian
Release=trixie
Architecture=x86-64

[Output]
Format=disk

[Content]
Packages=
    systemd
    systemd-boot
    linux-image-amd64
    udev
    sudo
    bash
    dbus
    systemd-resolved
    jq
    passwd
    login
ExtraTrees=.mkosi-secrets:/
RootPassword=!
RootShell=/usr/bin/false
BuildPackages=
    build-essential
    cmake
    pkg-config
    lua5.4
    liblua5.4-dev
    lua-lgi
    libcairo2-dev
    libdbus-1-dev
    libgdk-pixbuf-2.0-dev
    libglib2.0-dev
    libpango1.0-dev
    libstartup-notification0-dev
    libxdg-basedir-dev
    libxkbcommon-dev
    libxkbcommon-x11-dev
    libxcb1-dev
    libxcb-cursor-dev
    libxcb-icccm4-dev
    libxcb-keysyms1-dev
    libxcb-randr0-dev
    libxcb-shape0-dev
    libxcb-util0-dev
    libxcb-xinerama0-dev
    libxcb-xkb-dev
    libxcb-xrm-dev
    libxcb-xtest0-dev
    libxcb-xfixes0-dev
    libxcb-ewmh-dev
    git

[Build]
BuildSources=.

[Runtime]
CPUs=2
RAM=4G
Console=gui
