[Distribution]
Distribution=debian
Release=trixie
Architecture=x86-64

[Output]
Format=disk
OutputDirectory=mkosi.output

[Content]
Bootable=yes
Bootloader=systemd-boot
Packages=
    systemd
    systemd-sysv
    systemd-boot
    systemd-boot-efi
    systemd-boot-tools
    systemd-container
    systemd-repart
    dosfstools
    fdisk
    udev
    sudo
    bash
    dbus
    systemd-resolved
    passwd
    login
RootPassword=!
RootShell=/bin/false

[Build]
BuildSources=.

[Runtime]
CPUs=2
RAM=4G
Console=gui
