[Content]
Packages=
    ###########
    # TODO: temporarily use mesa-opencl-icd until intel-opencl-icd is available in Debian Trixie
    # This has lower performance. Other workarounds include building intel-opencl-icd from source or using the one from Debian Bookworm.
    mesa-opencl-icd
    #intel-opencl-icd
    ###########
    intel-media-va-driver-non-free
    intel-gpu-tools