[Content]
Packages=
    git
    git-delta
    iputils-ping
    ncdu
    curl
    wget
    vim
    htop
    tmux
    rsync
    less
    ca-certificates
    openssl
    fdisk
    exfatprogs
    ntfs-3g
    shellcheck
    python3.13-venv
    bubblewrap
