[Content]
Packages=
    git
    curl
    wget
    vim
    htop
    tmux
    rsync
    less
    ca-certificates
    # TODO: move to a dedicated profile for mkosi and related tools
    jq
    mkosi
    openssl
    fdisk
    shellcheck
