# apt-keys.conf for the zoom-web profile.
KEY_1_NAME="zoom-mwt-repo"
KEY_1_URL="https://mirror.mwt.me/zoom/gpgkey"
KEY_1_FINGERPRINT="18867E2389335DC61479ED834DF6AF98B7BE5AC2"
KEY_1_OUT="etc/apt/keyrings/zoom-mwt-repo-key.gpg"
