[Partition]
Type=esp
Format=vfat
# Copy everything from /boot to the ESP
CopyFiles=/boot:/
# Ensure bootloader binaries are present as Debian doesn't place them in /boot
CopyFiles=/usr/lib/systemd/boot/efi/systemd-bootx64.efi:/EFI/BOOT/BOOTX64.EFI
CopyFiles=/usr/lib/systemd/boot/efi/systemd-bootx64.efi:/EFI/systemd/systemd-bootx64.efi
SizeMinBytes=1G
SizeMaxBytes=1G
