[Content]
Packages=
    network-manager
    network-manager-iwd
    iwd
    network-manager-applet
    wireless-regdb
    firmware-iwlwifi
    firmware-linux-nonfree
    firmware-realtek
    firmware-mediatek
