# Format: <KeyName> <EventValue> <Command>
# EventValue 1 = Key press, 2 = Key hold, 0 = Key release

KEY_DISPLAYTOGGLE    1    /usr/local/sbin/reactivate-screen.sh
KEY_F8               1    /usr/local/sbin/reactivate-screen.sh
