#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/lib/host-deps.sh
source "$PROJECT_ROOT/scripts/lib/host-deps.sh"

IMAGE_ID=""
IMAGE_VERSION=""
TARGET_ARCH=""
IMAGE_PATH=""
OUTPUT_DIR=""
ENTRY_TITLE="Debian Provisioning"
EXTRA_KERNEL_ARGS=""

usage() {
  cat <<'USAGE'
Usage: export-sysupdate-artifacts.sh --image-id ID --version VER --arch ARCH --image PATH --output-dir DIR [options]

Options:
  --entry-title TITLE        title to use in generated Boot Loader Specification entry
  --extra-kernel-args ARGS   extra host-specific kernel command line arguments
USAGE
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

trim() {
  local value="$1"
  value="${value#${value%%[![:space:]]*}}"
  value="${value%${value##*[![:space:]]}}"
  printf '%s\n' "$value"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --image-id)
      IMAGE_ID="${2:?missing image id}"
      shift 2
      ;;
    --version)
      IMAGE_VERSION="${2:?missing version}"
      shift 2
      ;;
    --arch)
      TARGET_ARCH="${2:?missing arch}"
      shift 2
      ;;
    --image)
      IMAGE_PATH="${2:?missing image path}"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="${2:?missing output dir}"
      shift 2
      ;;
    --entry-title)
      ENTRY_TITLE="${2:?missing entry title}"
      shift 2
      ;;
    --extra-kernel-args)
      EXTRA_KERNEL_ARGS="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

if ! ab_hostdeps_have_all_commands jq sfdisk; then
  ab_hostdeps_ensure_packages "sysupdate artifact export prerequisites" jq fdisk || exit 1
fi
ab_hostdeps_ensure_commands "sysupdate artifact export prerequisites" jq sfdisk || exit 1

[[ -n "$IMAGE_ID" ]] || die "--image-id is required"
[[ -n "$IMAGE_VERSION" ]] || die "--version is required"
[[ -n "$TARGET_ARCH" ]] || die "--arch is required"
[[ -f "$IMAGE_PATH" ]] || die "image not found: $IMAGE_PATH"
[[ -d "$OUTPUT_DIR" ]] || die "output directory not found: $OUTPUT_DIR"

need_cmd jq
need_cmd sfdisk
need_cmd dd
need_cmd sha256sum
need_cmd install

root_artifact="$OUTPUT_DIR/${IMAGE_ID}_${IMAGE_VERSION}_${TARGET_ARCH}.root.raw"
uki_artifact="$OUTPUT_DIR/${IMAGE_ID}_${IMAGE_VERSION}_${TARGET_ARCH}.efi"
entry_artifact="$OUTPUT_DIR/${IMAGE_ID}_${IMAGE_VERSION}_${TARGET_ARCH}.conf"
meta_artifact="$OUTPUT_DIR/${IMAGE_ID}_${IMAGE_VERSION}_${TARGET_ARCH}.artifacts.env"
checksums_artifact="$OUTPUT_DIR/SHA256SUMS"

partition_json="$(sfdisk --json "$IMAGE_PATH")"
sector_size="$(jq -r '.partitiontable.sectorsize // 512' <<<"$partition_json")"
[[ "$sector_size" =~ ^[0-9]+$ ]] || die "unable to determine sector size"

root_start="$(jq -r '
  .partitiontable.partitions
  | map(select((.type // "") | ascii_downcase != "c12a7328-f81f-11d2-ba4b-00a0c93ec93b"))
  | max_by(.size // 0)
  | .start // empty
' <<<"$partition_json")"
root_size="$(jq -r '
  .partitiontable.partitions
  | map(select((.type // "") | ascii_downcase != "c12a7328-f81f-11d2-ba4b-00a0c93ec93b"))
  | max_by(.size // 0)
  | .size // empty
' <<<"$partition_json")"

[[ "$root_start" =~ ^[0-9]+$ ]] || die "unable to determine root partition start sector"
[[ "$root_size" =~ ^[0-9]+$ ]] || die "unable to determine root partition size in sectors"

echo "==> Exporting root partition from image.raw"
dd if="$IMAGE_PATH" of="$root_artifact" bs="$sector_size" skip="$root_start" count="$root_size" status=none

uki_source=""
# Prefer an exact-named UKI produced by mkosi for THIS image-id /
# version. Fall back to a glob scoped to the same image-id so stale
# UKIs from a previous build of a different profile cannot be picked
# up just because they sort earlier alphabetically. The unconstrained
# wildcard search that used to live here had exactly that bug.
for candidate in \
    "$OUTPUT_DIR/${IMAGE_ID}_${IMAGE_VERSION}.efi" \
    "$OUTPUT_DIR/${IMAGE_ID}_${IMAGE_VERSION}_${TARGET_ARCH}.efi" \
    "$OUTPUT_DIR/${IMAGE_ID}.efi"; do
  if [[ -f "$candidate" ]]; then
    uki_source="$candidate"
    break
  fi
done
if [[ -z "$uki_source" ]]; then
  uki_source="$(find "$OUTPUT_DIR" -maxdepth 2 -type f -name "${IMAGE_ID}*.efi" ! -name 'BOOT*.EFI' ! -name 'systemd-boot*.efi' | sort | head -n1 || true)"
fi
[[ -n "$uki_source" ]] || die "unable to locate split-out UKI for image '${IMAGE_ID}' in $OUTPUT_DIR"
install -m 0644 "$uki_source" "$uki_artifact"

entry_options="root=PARTLABEL=${IMAGE_ID}_${IMAGE_VERSION} rw"
if [[ -n "$EXTRA_KERNEL_ARGS" ]]; then
  entry_options="$entry_options $(trim "$EXTRA_KERNEL_ARGS")"
fi

cat > "$entry_artifact" <<EOF2
# Generated by scripts/export-sysupdate-artifacts.sh
title ${ENTRY_TITLE} ${IMAGE_VERSION}
sort-key ${IMAGE_ID}
version ${IMAGE_VERSION}
uki /EFI/Linux/${IMAGE_ID}_${IMAGE_VERSION}_${TARGET_ARCH}.efi
options ${entry_options}
EOF2

cat > "$meta_artifact" <<EOF2
IMAGE_ID=${IMAGE_ID}
IMAGE_VERSION=${IMAGE_VERSION}
IMAGE_ARCH=${TARGET_ARCH}
ROOT_ARTIFACT=$(basename "$root_artifact")
UKI_ARTIFACT=$(basename "$uki_artifact")
ENTRY_ARTIFACT=$(basename "$entry_artifact")
EOF2

(
  cd "$OUTPUT_DIR"
  sha256sum "$(basename "$root_artifact")" "$(basename "$uki_artifact")" "$(basename "$entry_artifact")" > "$(basename "$checksums_artifact")"
)

echo "==> Wrote $(basename "$root_artifact")"
echo "==> Wrote $(basename "$uki_artifact")"
echo "==> Wrote $(basename "$entry_artifact")"
