#!/usr/bin/env bash
set -euo pipefail

if [[ -x /usr/lib/systemd/systemd-bless-boot ]]; then
  exec /usr/lib/systemd/systemd-bless-boot bad
fi

echo "ERROR: /usr/lib/systemd/systemd-bless-boot not found" >&2
exit 1
