[Content]
Packages=
    xorg
    xinit
    xterm
    awesome
    dbus-x11
    xauth
    spice-vdagent
    picom
    git
    curl
    vim
    build-essential
    lua-lgi

[Runtime]
KernelCommandLineExtra=video=1280x720
